const initialActivities = [
  {id:'DEMO-2026-084',location:'موقع تجريبي 01',type:'وقائية',start:'2026-08-12',end:'2026-08-13',status:'قيد التنفيذ',auditor:'مستخدم 01'},
  {id:'DEMO-2026-083',location:'موقع تجريبي 02',type:'تصحيحية',start:'2026-08-11',end:'2026-08-11',status:'مكتمل',auditor:'مستخدم 02'},
  {id:'DEMO-2026-082',location:'موقع تجريبي 03',type:'وقائية',start:'2026-08-10',end:'2026-08-12',status:'مكتمل',auditor:'مستخدم 03'},
  {id:'DEMO-2026-081',location:'موقع تجريبي 04',type:'طارئة',start:'2026-08-09',end:'2026-08-14',status:'مخطط',auditor:'فريق تجريبي'},
  {id:'DEMO-2026-080',location:'موقع تجريبي 05',type:'وقائية',start:'2026-08-08',end:'2026-08-09',status:'مكتمل',auditor:'مستخدم 04'}
];
const dataService = window.SOAData.create(initialActivities);
let activities = [];
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const titles={dashboard:'لوحة المؤشرات',activities:'سجل الأنشطة',ncr:'حالات عدم المطابقة',reports:'التقارير',users:'المستخدمون والصلاحيات',audit:'سجل التدقيق'};
const roles={admin:{label:'مسؤول النظام',name:'مدير تجريبي',canWrite:true,canAudit:true,canAdmin:true},reviewer:{label:'مراجع / مشرف',name:'مراجع تجريبي',canWrite:false,canAudit:true,canAdmin:false},editor:{label:'موظف إدخال',name:'مدخل تجريبي',canWrite:true,canAudit:false,canAdmin:false},viewer:{label:'قارئ فقط',name:'قارئ تجريبي',canWrite:false,canAudit:false,canAdmin:false}};
let session=null;
function safe(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function badge(status){return `<span class="badge ${status==='مكتمل'?'done':status==='قيد التنفيذ'?'progress':'planned'}">${safe(status)}</span>`}
function formatDate(d){return new Intl.DateTimeFormat('ar-SA',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'))}
function row(a,full=false){return `<tr><td><b>${safe(a.id)}</b></td><td>${safe(a.location)}</td><td>${safe(a.type)}</td><td>${formatDate(a.start)}</td>${full?`<td>${formatDate(a.end)}</td>`:''}<td>${badge(a.status)}</td><td>${safe(a.auditor)}</td></tr>`}
function render(){
  $('#recentRows').innerHTML=activities.slice(0,5).map(a=>row(a)).join('');
  const q=$('#activitySearch').value.trim().toLowerCase(), status=$('#statusFilter').value;
  const list=activities.filter(a=>(!q||Object.values(a).some(v=>String(v).toLowerCase().includes(q)))&&(!status||a.status===status));
  $('#activityRows').innerHTML=list.map(a=>row(a,true)).join('')||'<tr><td colspan="7">لا توجد نتائج مطابقة.</td></tr>';
  $('#activityCount').textContent=`عرض ${list.length} من ${activities.length} سجلات تجريبية`;
}
const demoUsers=[{name:'مدير تجريبي',role:'مسؤول النظام',permissions:['عرض','إضافة','تعديل','اعتماد','إدارة المستخدمين']},{name:'مراجع تجريبي',role:'مراجع / مشرف',permissions:['عرض','مراجعة','اعتماد','سجل التدقيق']},{name:'مدخل تجريبي',role:'موظف إدخال',permissions:['عرض','إضافة','تعديل سجلاته']},{name:'قارئ تجريبي',role:'قارئ فقط',permissions:['عرض التقارير']}];
function renderUsers(){$('#userRows').innerHTML=demoUsers.map(u=>`<tr><td><b>${safe(u.name)}</b></td><td>${safe(u.role)}</td><td>${u.permissions.map(p=>`<span class="permission-tag">${safe(p)}</span>`).join('')}</td><td><span class="badge done">نشط</span></td></tr>`).join('')}
async function renderAudit(){const log=await dataService.auditLog();$('#auditRows').innerHTML=log.map(x=>`<tr><td>${new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x.at))}</td><td>${safe(x.actor)}</td><td>${safe(x.action)}</td><td>${safe(x.recordId)}</td></tr>`).join('')||'<tr><td colspan="4">لا توجد عمليات مسجلة بعد.</td></tr>'}
function applySession(roleKey){const role=roles[roleKey]||roles.viewer;session={role:roleKey,...role};localStorage.setItem('soaDemoSession',JSON.stringify(session));$('#profileName').textContent=role.name;$('#profileRole').textContent=role.label;$('#profileInitials').textContent=role.name.split(' ').map(x=>x[0]).slice(0,2).join('');$$('.admin-only').forEach(x=>x.classList.toggle('hidden-by-role',!role.canAdmin));$$('.reviewer-only').forEach(x=>x.classList.toggle('hidden-by-role',!role.canAudit));$$('[data-open-form],#newNcrBtn').forEach(x=>x.classList.toggle('hidden-by-role',!role.canWrite));$('#loginScreen').classList.add('hidden');renderUsers();renderAudit()}
function switchView(view){if((view==='users'&&!session?.canAdmin)||(view==='audit'&&!session?.canAudit)){toast('ليس لديك صلاحية لهذه الصفحة');return}$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#pageTitle').textContent=titles[view];$('#sidebar').classList.remove('open');if(view==='audit')renderAudit();scrollTo(0,0)}
$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewLink));
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('soaTheme',document.documentElement.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('soaTheme')==='dark')document.documentElement.classList.add('dark');
$$('[data-open-form]').forEach(b=>b.onclick=()=>{$('#activityModal').classList.add('open');$('#activityModal').setAttribute('aria-hidden','false')});$$('[data-close]').forEach(b=>b.onclick=()=>{$('#activityModal').classList.remove('open');$('#activityModal').setAttribute('aria-hidden','true')});
$('#activityForm').onsubmit=async e=>{e.preventDefault();if(!session?.canWrite){toast('ليس لديك صلاحية الإضافة');return}const form=e.target,data=Object.fromEntries(new FormData(form));if(activities.some(a=>a.id.trim().toLowerCase()===data.id.trim().toLowerCase())){toast('رقم الفحص مستخدم مسبقاً');return}if(data.end<data.start){toast('تاريخ النهاية يجب ألا يسبق تاريخ البداية');return}const button=form.querySelector('[type="submit"]');button.disabled=true;try{const saved=await dataService.addActivity(data);activities.unshift(saved);render();form.reset();$('[data-close]').click();await updateSyncStatus();toast('تم الحفظ بأمان، والتغيير في طابور المزامنة')}catch{toast('تعذر الحفظ؛ لم يتم تغيير البيانات')}finally{button.disabled=false}};
$('#activitySearch').oninput=render;$('#statusFilter').onchange=render;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
$('#newNcrBtn').onclick=()=>toast('سيتم ربط نموذج NCR بقاعدة البيانات المركزية');$$('.report-card').forEach(b=>b.onclick=()=>toast('تم تجهيز التقرير للمرحلة التالية'));
$('#langBtn').onclick=()=>toast('الواجهة الإنجليزية ستكون ضمن الإصدار القادم');
$('#demoLoginBtn').onclick=()=>applySession($('#demoRole').value);$('#profileBtn').onclick=()=>{$('#loginScreen').classList.remove('hidden')};
$('#exportAuditBtn').onclick=async()=>{if(!session?.canAudit){toast('ليس لديك صلاحية عرض سجل التدقيق');return}const log=await dataService.auditLog(),csv=[['Time','Actor','Action','Record ID'],...log.map(x=>[x.at,x.actor,x.action,x.recordId])].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='SOA-Audit-Log.csv';a.click();URL.revokeObjectURL(a.href)};
$('#exportBtn').onclick=()=>{const head=['QC Index No','SS/Line','Maintenance Type','Start Date','End Date','Status','Auditor Name'];const csv=[head,...activities.map(a=>[a.id,a.location,a.type,a.start,a.end,a.status,a.auditor])].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='SOA-Activities-Demo.csv';a.click();URL.revokeObjectURL(a.href)};
const chart=[['مارس',310,262],['أبريل',345,301],['مايو',330,287],['يونيو',370,325],['يوليو',390,342],['أغسطس',355,288]];$('#chartBars').innerHTML=chart.map(([m,p,d])=>`<div class="bar-group"><i class="bar planned" style="height:${p/4}px"></i><i class="bar done" style="height:${d/4}px"></i><span class="bar-label">${m}</span></div>`).join('');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const el=e.target,end=+el.dataset.count,start=performance.now();function tick(now){const v=Math.min(1,(now-start)/800);el.textContent=Math.floor(end*v).toLocaleString('ar-SA');if(v<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);io.unobserve(el)}}));$$('[data-count]').forEach(el=>io.observe(el));
async function updateSyncStatus(){const el=$('#syncStatus'),pending=await dataService.pendingCount();el.querySelector('span').textContent=window.SOA_CONFIG.dataProvider==='sharepoint'?'SharePoint':'الوضع التجريبي الآمن';el.querySelector('b').textContent=pending?`${pending} تغييرات بانتظار الربط`:'البيانات المحلية متزامنة'}
async function boot(){try{activities=await dataService.listActivities();render();await updateSyncStatus();const saved=JSON.parse(localStorage.getItem('soaDemoSession')||'null');if(saved?.role)applySession(saved.role)}catch{activities=initialActivities;render();toast('تعذر تحميل مصدر البيانات')}}
window.addEventListener('online',updateSyncStatus);window.addEventListener('offline',updateSyncStatus);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});boot();
